name: learn_image_picker
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'







dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.0
  google_fonts: ^6.2.1
  clay_containers: ^0.3.4
  path_provider: ^2.1.3

  
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter





  flutter_lints: ^3.0.0
flutter:
  assets:
    - images/
  uses-material-design: true
